Cargo.lock, Cargo.toml, LICENSE.txt, build.rs, src/gui/about.rs
=> License & dependencies

.github/workflows/rust.yml
=> Continuous Integration

src/gui/cooltoolbar.rs, src/gui/hotkeys.rs, src/main.rs
=> workspace arrange, hotkeys

src/gui/hotkeys.rs
=> fix: Better workspace shortcuts

src/gui.rs
Closes #15 
Fixed by not cloning large vectors every frame.
=> fix: table performance

src/gui/playback_controls.rs, src/main.rs
=> Fix: Playback controls point to playing workspace

src/gui/cooltoolbar.rs
Closes #32 
Left out system theme.
=> feat: dark light modes

src/data.rs, src/main.rs
=> fix: Non-shuffled queue always starts at first song

Cargo.lock, Cargo.toml, src/data.rs, src/gui/hotkeys.rs, src/gui/playback_controls.rs, src/main.rs
=> Feat: Repeat

src/gui.rs
=> Feat: Distinguish active workspace

src/data.rs, src/gui.rs, src/main.rs
=> feat: file errors

src/main.rs
=> Fix: volume default

Cargo.lock, Cargo.toml, src/gui.rs, src/workspace/font_meta.rs, src/workspace/midi_meta.rs
=> Feat: File sizes

src/gui.rs, src/workspace.rs
=> Feat: Sorting

src/audio.rs, src/audio/error.rs, src/gui.rs, src/gui/cooltoolbar.rs, src/gui/playback_controls.rs, src/main.rs, src/workspace.rs, src/workspace/font_meta.rs, src/workspace/midi_meta.rs
=> Feat error handling

Cargo.lock, Cargo.toml, src/gui.rs, src/gui/about.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/playback_controls.rs, src/main.rs
=> Feat toasts

Cargo.lock, Cargo.toml, src/gui.rs
Closes #59 
Won't work properly in tables until next egui release.
=> Feat: Context menus

Cargo.lock, Cargo.toml, src/audio.rs, src/audio/error.rs, src/audio/midisource.rs, src/gui.rs, src/gui/about.rs, src/gui/conversions.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/playback_controls.rs, src/gui/workspace_select.rs, src/main.rs, src/workspace.rs, src/workspace/font_meta.rs, src/workspace/midi_meta.rs
I enabled some clippy lints I suggest, fixed them and also added anyhow.
=> Enable lints, add anyhow

src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/playback_controls.rs, src/gui/workspace_select.rs, src/player.rs
=> Refactor: player error handling

src/gui.rs, src/main.rs
=> Fix: Unfocused app doesn't continue queue

src/gui.rs, src/gui/fonts.rs, src/gui/songs.rs
=> Refactor: Separate Fonts & Songs gui to their own modules

.github/workflows/release.yml, .github/workflows/rust.yml, Cargo.lock, Cargo.toml, src/gui.rs, src/gui/playback_controls.rs, src/main.rs, src/player.rs, src/player/mediacontrols.rs
=> Feat: OS integrated media controls

Cargo.lock, Cargo.toml, README.md, src/gui/cooltoolbar.rs, src/gui/fonts.rs, src/gui/songs.rs, src/main.rs, src/player.rs, src/player/workspace.rs, src/player/workspace/enums.rs, src/player/workspace/error.rs, src/player/workspace/font_meta.rs, src/player/workspace/midi_meta.rs, src/player/workspace/serialize.rs
=> Feat: Proper State Serialization

src/main.rs, src/player.rs, src/player/audio.rs, src/player/audio/error.rs
=> App logic update thread

src/main.rs, src/player.rs
=> Feat: Auto refresh directory list

src/gui/fonts.rs, src/gui/keyboard_shortcuts.rs, src/gui/songs.rs, src/gui/workspace_select.rs, src/player.rs, src/player/workspace.rs
=> Feat: File context menu: add to another workspace

Cargo.lock, Cargo.toml, src/gui/cooltoolbar.rs, src/gui/workspace_select.rs, src/player.rs, src/player/workspace.rs, src/player/workspace/font_meta.rs, src/player/workspace/midi_meta.rs, src/player/workspace/serialize.rs
=> Feat: Portable workspace

src/gui.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs
=> Fix: Pressing space while typing pauses

src/gui/fonts.rs, src/player.rs, src/player/workspace.rs
=> Feat: Default soundfont

src/main.rs
=> Fix: Play opened songs automatically

src/gui.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/workspace_select.rs
=> Feat: Workspace context menu

src/player.rs
=> Fix: Buggy workspace index handling

src/player.rs
=> Fix: Prevent opening multiple instances of same workspace

src/gui.rs, src/gui/cooltoolbar.rs, src/gui/file_dialogs.rs, src/gui/keyboard_shortcuts.rs, src/gui/workspace_select.rs, src/player.rs
=> Feat: save as

src/gui/cooltoolbar.rs, src/gui/file_dialogs.rs, src/gui/keyboard_shortcuts.rs, src/gui/workspace_select.rs, src/player.rs
=> Feat: Duplicate workspace

.gitignore, src/gui/cooltoolbar.rs, src/gui/fonts.rs, src/gui/keyboard_shortcuts.rs, src/gui/workspace_select.rs, src/player/workspace.rs, src/player/workspace/serialize_workspace.rs
=> Feat-unsaved-indicator

src/gui.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/modals/shortcuts.rs
=> Fix: Shortcut consume order

src/player.rs, src/player/workspace.rs
=> Fix: Workspace delete crash

src/gui.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/modals/mod.rs, src/gui/modals/settings.rs, src/gui/modals/shortcuts.rs, src/gui/workspace_select.rs, src/main.rs, src/player.rs, src/player/serialize_player.rs, src/player/workspace/serialize_workspace.rs
=> Feat: Settings

src/gui/keyboard_shortcuts.rs, src/gui/modals/shortcuts.rs
=> Feat: Repeat shortcut

src/player.rs
=> Fix: kind of dumb workspace index handling on removal

src/gui/cooltoolbar.rs, src/gui/modals/shortcuts.rs, src/gui/workspace_select.rs
=> Design: Rename appdata / builtin to app memory

src/gui.rs, src/gui/actions.rs, src/gui/cooltoolbar.rs, src/gui/fonts.rs, src/gui/songs.rs, src/gui/workspace_select.rs
=> Design: merge workspace menu to file menu

src/gui/cooltoolbar.rs, src/gui/modals/settings.rs
=> Design: Move theme toggle to settings

src/gui.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/modals/mod.rs, src/gui/modals/shortcuts.rs, src/main.rs, src/player.rs, src/player/mediacontrols.rs
=> Feat: Shortcuts for quit and shortcut modal

src/gui.rs, src/gui/modals/mod.rs, src/player.rs, src/player/workspace.rs
=> Feat: Unsaved close prompt

src/gui/actions.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/modals/shortcuts.rs, src/player.rs
=> Feat: Reopen tabs

src/gui.rs, src/gui/cooltoolbar.rs, src/gui/keyboard_shortcuts.rs, src/gui/workspace_select.rs
Closes #166 
Hopefully fixed for real this time.
=> Fix: Shortcuts on textbox

src/gui/playback_controls.rs
=> Fix: Crash when shuffling empty queue

src/gui/soundfont_library.rs
=> Feature: Indicate playlist font override in font lib

src/gui/modals/settings.rs, src/player.rs, src/player/serialize_player.rs
=> Feat: Dev option app directories

src/player/playlist/serialize_playlist.rs, src/player/serialize_player.rs
=> Refactor: Font/song idx/sort is stored in app memory

src/gui/modals/file_dialogs.rs, src/main.rs, src/player/playlist/serialize_playlist.rs
=> Design: Rename workspace format to playlist

src/player/playlist.rs
=> Fix: Unnecessary unsaved flags

src/player/playlist.rs
=> Fix: Descending time song sort

src/player/soundfont_library.rs
=> Fix: Fontlib No subdirs

src/player/soundfont_library.rs, src/player/soundfont_list.rs
=> Fix: Fontlib subdirs

src/gui/playlist_fonts.rs, src/gui/playlist_songs.rs, src/player/soundfont_list.rs
=> Fix: Playlist add individual files

Cargo.toml, src/gui/playback_controls.rs, src/player.rs, src/player/audio.rs, src/player/audio/midisource.rs, src/player/audio/sequencer.rs
=> Feat: Seeking

src/gui/playlist_fonts.rs, src/gui/soundfont_library.rs, src/player.rs, src/player/audio.rs
=> Feat: Font change on the go

src/gui.rs, src/gui/midi_inspector.rs, src/gui/playlist_songs.rs, src/main.rs, src/midi_inspector.rs
=> Feat: Midi inspector

src/gui/midi_inspector.rs
=> Feat: Midi inspector raw data

src/player/audio/sequencer.rs
=> Fix: Unhandled CC event 0x62

Cargo.toml, src/player/audio.rs, src/player/audio/midisequencer.rs, src/player/audio/midisource.rs, src/player/audio/midisynth.rs
=> Refactor: Separate midisynth and midiseq

src/player.rs, src/player/audio/midisource.rs
=> Fix: Broken volume slider

src/gui.rs, src/gui/midi_inspector.rs, src/midi_inspector.rs
=> Feat: Inspector track names & collapse

src/gui/playlist_fonts.rs
=> fix: unselecting playlist font doesn't refresh

Cargo.lock, Cargo.toml, src/gui/midi_inspector/midi_renderer.rs, src/gui/midi_inspector/mod.rs, src/player.rs, src/player/audio/midisequencer.rs, src/player/audio/midisource.rs, src/player/audio/mod.rs, src/player/error.rs, src/player/midi_inspector/midi_renderer.rs, src/player/midi_inspector/mod.rs, src/player/midi_inspector/preset_mapper.rs, src/player/playlist/font_meta.rs, src/player/playlist/midi_meta.rs, src/player/soundfont_library.rs
=> feat: Render

src/player/error.rs, src/player/playlist.rs
=> refactor: Playlist check for duplicates

src/gui/playlist_fonts.rs, src/gui/playlist_songs.rs, src/player.rs, src/player/playlist.rs, src/player/playlist/font_meta.rs, src/player/playlist/midi_meta.rs, src/player/soundfont_list.rs
=> fix: Crash on font removal

src/gui/midi_inspector/event_browser.rs, src/gui/midi_inspector/midi_renderer.rs, src/gui/midi_inspector/preset_mapper.rs, src/gui/playback_controls.rs, src/gui/playlist_fonts.rs, src/gui/playlist_songs.rs, src/gui/soundfont_library.rs, src/player.rs, src/player/error.rs, src/player/mediacontrols.rs, src/player/midi_inspector/mod.rs, src/player/midi_inspector/preset_mapper.rs, src/player/playlist.rs, src/player/playlist/font_meta.rs, src/player/playlist/midi_meta.rs, src/player/playlist/serialize_playlist.rs, src/player/serialize_player.rs, src/player/soundfont_library.rs, src/player/soundfont_list.rs
=> refactor: meta handling

src/player/mediacontrols.rs
=> fix: crash on mediacontrols attach failure
